-   id: poetry
    name: poetry
    description: ''
    entry: poetry-wrapper
    language: python
    'types': [file]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '0'
