-   id: poetry
    name: poetry
    description: ''
    entry: poetry
    language: python
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
